
// Generated by Cadence Encounter(R) RTL Compiler RC14.24 - v14.20-s034_1

// Verification Directory fv/adder_2bit 

module adder_2bit(clk, a, b, sum, cout);
  input clk;
  input [1:0] a, b;
  output [1:0] sum;
  output cout;
  wire clk;
  wire [1:0] a, b;
  wire [1:0] sum;
  wire cout;
  wire a0, a1, b0, b1, n_0, n_2, n_4, n_5;
  wire n_7, n_9, n_12, n_13, n_14, n_32, n_36, n_40;
  wire n_44, n_50, n_53, n_54;
  INVx8_ASAP7_75t_R g191(.A (n_32), .Y (sum[1]));
  INVx8_ASAP7_75t_R g193(.A (n_40), .Y (cout));
  DFFHQNx4_ASAP7_75t_R f6_q_reg(.CLK (clk), .D (n_9), .QN (n_13));
  DFFHQNx4_ASAP7_75t_R f7_q_reg(.CLK (clk), .D (n_7), .QN (n_12));
  XNOR2xp5_ASAP7_75t_R_v2 g195(.A (n_54), .B (n_5), .Y (n_9));
  INVx8_ASAP7_75t_R g196(.A (n_36), .Y (sum[0]));
  MAJIxp5_ASAP7_75t_R g198(.A (n_54), .B (n_2), .C (n_0), .Y (n_7));
  DFFHQNx4_ASAP7_75t_R f5_q_reg(.CLK (clk), .D (n_4), .QN (n_14));
  XOR2xp5_ASAP7_75t_R_v2 g199(.A (a1), .B (b1), .Y (n_5));
  XOR2xp5_ASAP7_75t_R_v2 g200(.A (n_50), .B (n_44), .Y (n_4));
  HB1xp67_ASAP7_75t_R g204(.A (b1), .Y (n_2));
  HB1xp67_ASAP7_75t_R g208(.A (a1), .Y (n_0));
  DFFHQNx4_ASAP7_75t_R f4_q_reg(.CLK (clk), .D (b[1]), .QN (b1));
  DFFHQNx4_ASAP7_75t_R f3_q_reg(.CLK (clk), .D (b[0]), .QN (b0));
  DFFHQNx4_ASAP7_75t_R f1_q_reg(.CLK (clk), .D (a[0]), .QN (a0));
  DFFHQNx4_ASAP7_75t_R f2_q_reg(.CLK (clk), .D (a[1]), .QN (a1));
  BUFx12_ASAP7_75t_R drc(.A (n_13), .Y (n_32));
  BUFx12_ASAP7_75t_R drc227(.A (n_14), .Y (n_36));
  BUFx12_ASAP7_75t_R drc230(.A (n_12), .Y (n_40));
  HB1xp67_ASAP7_75t_R drc_bufs233(.A (a0), .Y (n_44));
  HB1xp67_ASAP7_75t_R drc_bufs238(.A (b0), .Y (n_50));
  INVxp33_ASAP7_75t_R g3(.A (n_53), .Y (n_54));
  NOR2x1_ASAP7_75t_R g2(.A (a0), .B (b0), .Y (n_53));
endmodule

