/*
###############################################################
#  Generated by:      Cadence Encounter 14.27-s035_1
#  OS:                Linux x86_64(Host ID eecad31.eas.asu.edu)
#  Generated on:      Thu Feb 23 13:36:23 2017
#  Design:            adder_2bit
#  Command:           saveNetlist adder_2bit_netlist.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 14.27-s035_1
#  OS:                Linux x86_64(Host ID eecad31.eas.asu.edu)
#  Generated on:      Thu Feb 23 12:30:17 2017
#  Design:            adder_2bit
#  Command:           saveDesign adder_2bit_prefp.enc
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler RC14.24 - v14.20-s034_1
// Verification Directory fv/adder_2bit 
module adder_2bit (
	clk, 
	a, 
	b, 
	sum, 
	cout);
   input clk;
   input [1:0] a;
   input [1:0] b;
   output [1:0] sum;
   output cout;

   // Internal wires
   wire FE_OFN20_b1;
   wire FE_OFN19_n_54;
   wire FE_OFN18_b1;
   wire FE_OFN16_b0;
   wire FE_OFN15_n_13;
   wire FE_OFN14_b1;
   wire FE_OFN13_n_14;
   wire FE_OFN12_n_12;
   wire FE_OFN11_a1;
   wire FE_OFN10_b1;
   wire FE_OFN9_a1;
   wire FE_OFN8_b1;
   wire FE_OFN7_n_13;
   wire FE_OFN6_n_12;
   wire FE_OFN5_n_13;
   wire FE_OFN4_n_14;
   wire FE_OFN3_b0;
   wire FE_OFN2_a0;
   wire FE_OFN1_a1;
   wire FE_OFN0_b1;
   wire a0;
   wire a1;
   wire b0;
   wire b1;
   wire n_4;
   wire n_5;
   wire n_7;
   wire n_9;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_53;
   wire n_54;

   BUFx4_ASAP7_75t_R FE_OFC20_b1 (.Y(FE_OFN20_b1),
	.A(FE_OFN14_b1));
   BUFx4_ASAP7_75t_R FE_OFC19_n_54 (.Y(FE_OFN19_n_54),
	.A(n_54));
   BUFx6f_ASAP7_75t_R FE_OFC18_b1 (.Y(FE_OFN18_b1),
	.A(FE_OFN0_b1));
   BUFx4_ASAP7_75t_R FE_OFC16_b0 (.Y(FE_OFN16_b0),
	.A(FE_OFN3_b0));
   BUFx12f_ASAP7_75t_R FE_OFC15_n_13 (.Y(FE_OFN15_n_13),
	.A(FE_OFN7_n_13));
   HB1xp67_ASAP7_75t_R FE_OFC14_b1 (.Y(FE_OFN14_b1),
	.A(FE_OFN18_b1));
   BUFx6f_ASAP7_75t_R FE_OFC13_n_14 (.Y(FE_OFN13_n_14),
	.A(n_14));
   BUFx6f_ASAP7_75t_R FE_OFC12_n_12 (.Y(FE_OFN12_n_12),
	.A(n_12));
   BUFx8_ASAP7_75t_R FE_OFC11_a1 (.Y(FE_OFN11_a1),
	.A(FE_OFN1_a1));
   BUFx6f_ASAP7_75t_R FE_OFC10_b1 (.Y(FE_OFN10_b1),
	.A(FE_OFN20_b1));
   BUFx6f_ASAP7_75t_R FE_OFC9_a1 (.Y(FE_OFN9_a1),
	.A(FE_OFN11_a1));
   BUFx6f_ASAP7_75t_R FE_OFC8_b1 (.Y(FE_OFN8_b1),
	.A(FE_OFN10_b1));
   BUFx6f_ASAP7_75t_R FE_OFC7_n_13 (.Y(FE_OFN7_n_13),
	.A(n_13));
   BUFx12f_ASAP7_75t_R FE_OFC6_n_12 (.Y(FE_OFN6_n_12),
	.A(FE_OFN12_n_12));
   BUFx12f_ASAP7_75t_R FE_OFC5_n_13 (.Y(FE_OFN5_n_13),
	.A(FE_OFN15_n_13));
   BUFx12f_ASAP7_75t_R FE_OFC4_n_14 (.Y(FE_OFN4_n_14),
	.A(FE_OFN13_n_14));
   BUFx6f_ASAP7_75t_R FE_OFC3_b0 (.Y(FE_OFN3_b0),
	.A(b0));
   BUFx6f_ASAP7_75t_R FE_OFC2_a0 (.Y(FE_OFN2_a0),
	.A(a0));
   BUFx10_ASAP7_75t_R FE_OFC1_a1 (.Y(FE_OFN1_a1),
	.A(a1));
   BUFx6f_ASAP7_75t_R FE_OFC0_b1 (.Y(FE_OFN0_b1),
	.A(b1));
   INVx13_ASAP7_75t_R g191 (.Y(sum[1]),
	.A(FE_OFN5_n_13));
   INVx13_ASAP7_75t_R g193 (.Y(cout),
	.A(FE_OFN6_n_12));
   DFFHQNx4_ASAP7_75t_R f6_q_reg (.QN(n_13),
	.D(n_9),
	.CLK(clk));
   DFFHQNx4_ASAP7_75t_R f7_q_reg (.QN(n_12),
	.D(n_7),
	.CLK(clk));
   XNOR2xp5_ASAP7_75t_R_v2 g195 (.Y(n_9),
	.B(n_5),
	.A(n_54));
   INVx13_ASAP7_75t_R g196 (.Y(sum[0]),
	.A(FE_OFN4_n_14));
   MAJIxp5_ASAP7_75t_R g198 (.Y(n_7),
	.C(FE_OFN9_a1),
	.B(FE_OFN8_b1),
	.A(FE_OFN19_n_54));
   DFFHQNx4_ASAP7_75t_R f5_q_reg (.QN(n_14),
	.D(n_4),
	.CLK(clk));
   XOR2xp5_ASAP7_75t_R_v1 g199 (.Y(n_5),
	.B(FE_OFN18_b1),
	.A(FE_OFN1_a1));
   XOR2xp5_ASAP7_75t_R_v2 g200 (.Y(n_4),
	.B(FE_OFN2_a0),
	.A(FE_OFN3_b0));
   DFFHQNx4_ASAP7_75t_R f4_q_reg (.QN(b1),
	.D(b[1]),
	.CLK(clk));
   DFFHQNx4_ASAP7_75t_R f3_q_reg (.QN(b0),
	.D(b[0]),
	.CLK(clk));
   DFFHQNx4_ASAP7_75t_R f1_q_reg (.QN(a0),
	.D(a[0]),
	.CLK(clk));
   DFFHQNx4_ASAP7_75t_R f2_q_reg (.QN(a1),
	.D(a[1]),
	.CLK(clk));
   INVx1_ASAP7_75t_R g3 (.Y(n_54),
	.A(n_53));
   NOR2xp33_ASAP7_75t_R g2 (.Y(n_53),
	.B(FE_OFN16_b0),
	.A(FE_OFN2_a0));
endmodule

